# Copyright (c)  2025  OceanApocalypseStudios
# Permission is granted to copy, distribute and/or modify this document
# under the terms of the GNU Free Documentation License, Version 1.3
# or any later version published by the Free Software Foundation;
# with no Invariant Sections, no Front-Cover Texts, and no Back-Cover Texts.


# Project information
site_name: Red Sea Markup Language
site_url: https://oceanapocalypsestudios.github.io/RedSeaMarkupLanguage/
site_author: OceanApocalypseStudios
site_description: >-
  The modern and robust language for defining OS-dependent logic paths.


# Repository
repo_name: OceanApocalypseStudios/RedSeaMarkupLanguage
repo_url: https://github.com/OceanApocalypseStudios/RedSeaMarkupLanguage/ 


# Copyright
copyright: Copyright &copy; 2025  OceanApocalypseStudios


# Configuration
theme:
  name: material
  custom_dir: material/overrides

  # Fonts
  font:
    text: Roboto
    code: Roboto Mono

  # Colors
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to system preference mode
  
  # Language
  language: en

  # Features
  features:
    # Content actions and code related
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.code.select

    # Tooltips
    - content.tooltips
    # - content.footnote.tooltips

    # Header
    # - header.autohide
    
    # Linked tabs for blocks
    - content.tabs.link

    # Navigation
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - navigation.path

    # Search
    - search.highlight
    - search.share
    - search.suggest

    # ToC
    - toc.follow
    # - toc.integrate
  
  # Logo and Iconography
  logo: img/logo.png
  favicon: img/favicon.ico
  icon:
    top: fontawesome/solid/angles-up
    repo: fontawesome/brands/github


# Material Plugins
plugins:
  - social # Social cards - embeds 
  - search # Global docs searching


# Extras that should be built, but aren't docs
extra:
  # Material does not use native favicons
  favicon: img/favicon.ico

  # Social links
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/OceanApocalypseStudios
    - icon: material/web
      link: https://oceanapocalypsestudios.org/


# CSS for advanced customization
extra_css:
  - stylesheets/extra.css


# Folders to watch for (outside docs)
watch:
  - includes


# Hooks
hooks:
  - material/overrides/hooks/shortcodes.py


# Markdown extensions
markdown_extensions:
  # HTML Attributes in Markdown
  - attr_list

  # Table of contents
  - toc:
      permalink: true
      title: On this page

  # Markdown
  - pymdownx.details

  # Tabbed content
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true

  # Better Formatting
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde

  # Admonitions
  - admonition

  # abbreviations
  - abbr

  # Code blocks
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite

  # definition lists - pretty good
  - def_list

  # snippets
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  
  # tasklists
  - pymdownx.tasklist:
      custom_checkbox: true # better checkboxes
  
  # Better Image Manipulation
  - md_in_html
  - pymdownx.blocks.caption

  # Tables
  - tables

  # Emojis
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

  # Instant Previews
  - material.extensions.preview:
      configurations:
        - targets:
            include:
              - api/*
              - cli/*
              - language/*
              - contributing.md


# Navigation
  # Small reminder that all documentation must be included
  # here, as otherwise, it won't be built!!
nav:
  - Home: index.md
  - Why use RSML?:
    - Why RSML?: why/index.md
    - Alternatives to RSML: why/alternatives.md
  - Language:
    - RSML as a Language: language/index.md
    - RSML Implementations: language/implementations.md
  - API:
    - RSML as an API: api/index.md
    - Guides:
      - About our Guides: api/guides/index.md
      - Easy:
        - Hello, World!: api/guides/hello-world.md
    - Usage Demos: api/demos.md 
    - C#:
      - Getting Started: api/csharp/index.md
      - Reference:
        - Overview: api/csharp/reference/index.md
        - RSML:
          - Namespace Overview: api/csharp/reference/RSML/index.md
          - RSDocument: api/csharp/reference/RSML/RSDocument.md
        - RSML.Exceptions:
          - Namespace Overview: api/csharp/reference/RSML.Exceptions/index.md
          - ImmutableActionException: api/csharp/reference/RSML.Exceptions/ImmutableActionException.md
          - RSMLRuntimeException: api/csharp/reference/RSML.Exceptions/RSMLRuntimeException.md
          - UndefinedActionException: api/csharp/reference/RSML.Exceptions/UndefinedActionException.md
          - UndefinedSpecialException: api/csharp/reference/RSML.Exceptions/UndefinedSpecialException.md
        - RSML.Parser:
          - Namespace Overview: api/csharp/reference/RSML.Parser/index.md
          - OperatorType: api/csharp/reference/RSML.Parser/OperatorType.md
          - ReadyToGoParser: api/csharp/reference/RSML.Parser/ReadyToGoParser.md
          - RSParser: api/csharp/reference/RSML.Parser/RSParser.md
    - Python:
      - Getting Started: api/python/index.md
      - Reference:
        - RedSeaCLIExecutable: api/python/RedSeaCLIExecutable.md
        - RedSeaDocument: api/python/RedSeaDocument.md
    #- C++:
      #- Getting Started: api/cpp/index.md
      #- Reference: api/cpp/reference.md
  - CLI:
    - RSML as a CLI: cli/index.md
    - Commands: cli/commands.md
    - Real-world usage: cli/examples.md
  - Contributing: contributing.md
  - Changelog: changelog.md
  - Conventions: conventions.md


# Copyright (c)  2025  OceanApocalypseStudios
# Permission is granted to copy, distribute and/or modify this document
# under the terms of the GNU Free Documentation License, Version 1.3
# or any later version published by the Free Software Foundation;
# with no Invariant Sections, no Front-Cover Texts, and no Back-Cover Texts.
